name: release

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - "mod-folder/**"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug - list files
        run: ls -la mod-folder/
      - name: Zip folder
        run: cd mod-folder && zip -r ../music.zip assets pack.mcmeta pack.png

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: music-${{  github.run_number}}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
